name: Backend CI

on: push

jobs:
  run:
    name: Run on Python ${{ matrix.python-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10" ]  # can use other python versions
        os: [ "ubuntu-latest" ]  # can test in other OS

    steps:
      - uses: actions/checkout@v3

      - name: Check for CRLF endings
        uses: erclu/check-crlf@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install hatch
        run: python -m pip install -U pip hatch

      - name: Lint
        run: hatch run lint

      - name: Test
        run: hatch run cov

  integration:
    env:
      CORS_ORIGIN: NOT_NEEDED

    runs-on: ubuntu-latest
    # only run on pull requests and main branch
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Download database
        run: |
          wget https://github.com/neuml/txtai/releases/download/v1.1.0/tests.gz
          mv tests.gz articles.sqlite.gz
          gunzip articles.sqlite

      - name: Install hatch
        run: python -m pip install hatch

      - name: Run integration tests
        run: hatch run integration
